### ISSUE TITLE
Discussion: Packages namings

### ISSUE THREAD

**Issue by diedsmiling** [loomjs/loom#4]
(_This discussion started here: https://github.com/loomjs/loom/pull/3_)

Loom will have two main  packages.  Suggested names where:

**Registry** - for centralised loom modules store.
**Loom** - Loom runtime itself

I think everybody is cool with **loom**,  but there are some doubts regarding **Registry**. Alternative names would be "Modules store", "Modules state". 

The idea is to pick a name that would make learning curve less steep. Since it's an open source project, we are interested in keeping entry treshold as low as possible.

**Comment by diedsmiling** [comment]
My thoughts and suggestions:

**Registry**: 
Similar to npm registry. It has similar purpose, but not only.

**Modules store**:
People might think of a physical storage where bundles themself would be stored. 

**Modules state**:
Too many states in react ecosystem already. 

**Repository**:
Don't see any disadvantages here.

**Vault** 
More seldom definition in software development world. Might not be clear from the very beginning.

**Comment by cassiocardoso** [comment]
I like `registry` and `repository`.

The only downside of `repository` is that it's very similar to GitHub repos, so, depending on the context clarification would be needed.

Vault is also nice but I'm not sure about it. 🤔

**Comment by sircelsius** [comment]
My preference goes to `registry`, I find it to be the most representative

**Comment by omarahm** [comment]
I vote for `registry` as well, I liked store/state until I read your description which makes a lot of sense.

**Comment by diedsmiling** [comment]
I also have nothing against registry. 
So **registry** it is!
